import React from 'react';

const Legal: React.FC = () => {
  return (
    <section className="pt-32 pb-20 px-6 min-h-screen">
      <div className="max-w-3xl mx-auto">
        <h1 className="font-display text-4xl mb-12 text-white">Protocol Governance</h1>
        
        <div className="space-y-12 text-gray-400 font-light leading-relaxed">
          <div className="space-y-4">
            <h2 className="text-white text-lg font-normal">1. Genetic Data Sovereignty</h2>
            <p>
              Bio-Genesis Systems adheres to the Universal Genomic Privacy Accord (UGPA 2029). All synthesized sequences remain the intellectual property of the originating node until clinical deployment. Our neural engine operates on a zero-knowledge proof basis for all genetic material ingested.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className="text-white text-lg font-normal">2. Liability Limitation</h2>
            <p>
              Simulations generated by our engine are probabilistic predictions based on evolutionary models. Bio-Genesis accepts no liability for in vivo deviations resulting from environmental variables outside the controlled simulation parameters.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className="text-white text-lg font-normal">3. Node Access</h2>
            <p>
              Access to the platform is restricted to accredited research institutions. Unauthorized redistribution of API tokens will result in immediate termination of the handshake protocol and blacklisting of the institutional IP range.
            </p>
          </div>

           <div className="p-6 bg-white/5 rounded-xl border border-white/10 mt-12">
            <p className="text-xs font-mono text-gray-500">
              LAST UPDATED: CYCLE 882.9A <br/>
              COMPLIANCE STATUS: VERIFIED
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Legal;